version: '3.7'
services:

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_VERSION=2
      - CF_EMAIL=email@example.com
      - CF_TOKEN=1234
      - TARGET_DOMAIN=host.example.org
      - DOMAIN1=example.org
      - DOMAIN1_ZONE_ID=1234567890
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true
